export default {
  MOEYS_BACII_CERTIFICATE: "MOEYS_BACII_CERTIFICATE",
  CADT_DSE_ERA_CERTIFICATE: "CADT_DSE_ERA_CERTIFICATE",
  AUPP_BACHELOR_CERTIFICATE: "AUPP_BACHELOR_CERTIFICATE",
  MPTC_RECOGNITION_CERTIFICATE: "MPTC_GDA_COMPETITION_CERTIFICATE",
  NUM_BACHELOR_CERTIFICATE: "NUM_BACHELOR_CERTIFICATE",
  MPTC_GDA_WORKSHOP_CERTIFICATE: "MPTC_GDA_WORKSHOP_CERTIFICATE",
  MoEYS_STUDENT_CARD_KH: "MoEYS_STUDENT_CARD_KH",
  MPTC_GDA_TECHO_DIGITAL_SCHOLARSHIP_CERTIFICATE:
    "MPTC_GDA_TECHO_DIGITAL_SCHOLARSHIP_CERTIFICATE",
  MPTC_GDA_WORKSHOP_PAILIN_CERTIFICATE: "MPTC_GDA_WORKSHOP_PAILIN_CERTIFICATE",
  MPTC_GDA_WORKSHOP_KAMPONG_THOM_CERTIFICATE:
    "MPTC_GDA_WORKSHOP_KAMPONG_THOM_CERTIFICATE",
  ITC_ENGINEER_DEGREE_CERTIFICATE: "ITC_ENGINEER_DEGREE_CERTIFICATE",
  MPTC_GDA_DATA_GOVERNANCE_WORKSHOP_CERTIFICATE:
    "MPTC_GDA_DATA_GOVERNANCE_WORKSHOP_CERTIFICATE",
  CADT_BACHELOR_DEGREE: "CADT_BACHELOR_DEGREE",
  CADT_BACHELOR_CERTIFICATE: "CADT_BACHELOR_CERTIFICATE",
  ITC_BACHELOR_DEGREE: "ITC_BACHELOR_DEGREE",
  NUM_MASTER_CERTIFICATE: "NUM_MASTER_CERTIFICATE",
  NUM_PHD_CERTIFICATE: "NUM_PHD_CERTIFICATE",
  MPTC_GDA_WORKSHOP_COORDINATOR_CERTIFICATE:
    "MPTC_GDA_WORKSHOP_COORDINATOR_CERTIFICATE",
  MPTC_GDA_WORKSHOP_GUEST_SPEAKER_CERTIFICATE:
    "MPTC_GDA_WORKSHOP_GUEST_SPEAKER_CERTIFICATE",
  MPTC_GDA_WORKSHOP_PREAH_SIHANOUK_CERTIFICATE:
    "MPTC_GDA_WORKSHOP_PREAH_SIHANOUK_CERTIFICATE",
  MPTC_DG_UNDESA_WORKSHOP_CERTIFICATE: "MPTC_DG_UNDESA_WORKSHOP_CERTIFICATE",
  MPTC_DG_OECD_WORKSHOP_CERTIFICATE: "MPTC_DG_OECD_WORKSHOP_CERTIFICATE",
  MPTC_GDA_WORKSHOP_EXTERNAL_CERTIFICATE:
    "MPTC_GDA_WORKSHOP_EXTERNAL_CERTIFICATE",
  MPTC_GDA_INTERNSHIP_CERTIFICATE: "MPTC_GDA_INTERNSHIP_CERTIFICATE",
  MPTC_RUPP_INTERNSHIP_CERTIFICATE: "MPTC_RUPP_INTERNSHIP_CERTIFICATE",
  NIPH_MASTER_DEGREE: "NIPH_MASTER_DEGREE",
  NIE_STUDENT_ID_CARD: "NIE_STUDENT_ID_CARD",
  NIE_STAFF_ID_CARD: "NIE_STAFF_ID_CARD",
  NUBB_BACHELOR_DEGREE: "NUBB_BACHELOR_DEGREE",
  MOEYS_CERTIFICATE_APPRECIATE_YEARLY: "MOEYS_CERTIFICATE_APPRECIATE_YEARLY",
  MoEYS_STUDENT_APPRECIATION_CERTIFICATE:
    "MoEYS_STUDENT_APPRECIATION_CERTIFICATE",
  MoEYS_STUDENT_COMMENDATION_CERTIFICATE:
    "MoEYS_STUDENT_COMMENDATION_CERTIFICATE",
  MoEYS_STUDENT_MOTIVATION_LETTER_CERTIFICATE:
    "MoEYS_STUDENT_MOTIVATION_LETTER_CERTIFICATE",
  MPTC_LETTER_WRITING_COMPETITION_CERTIFICATE:
    "MPTC_LETTER_WRITING_COMPETITION_CERTIFICATE",
  AUPP_MASTER_CERTIFICATE: "AUPP_MASTER_CERTIFICATE",
  NUBB_MASTER_DEGREE: "NUBB_MASTER_DEGREE",
  SRU_BACHELOR_DEGREE: "SRU_BACHELOR_DEGREE",
  RUFA_BACHELOR_DEGREE: "RUFA_BACHELOR_DEGREE",
  NUCK_BACHELOR_DEGREE: "NUCK_BACHELOR_DEGREE",
  UKCertificateTableLayout: "UKCertificateTableLayout",
  NIE_MASTER_DEGREE: "NIE_MASTER_DEGREE",
  NIE_INSPECTOR_CERTIFICATE: "NIE_INSPECTOR_CERTIFICATE",
  CADT_CERTIFICATE_OF_COMPLETION: "CADT_CERTIFICATE_OF_COMPLETION",
  UHST_BACHELOR_DEGREE: "UHST_BACHELOR_DEGREE",
  UHST_ASSOCIATE_DEGREE: "UHST_ASSOCIATE_DEGREE",
  NIA_BACHELOR_DEGREE: "NIA_BACHELOR_DEGREE",
  KSIT_BACHELOR_DEGREE: "KSIT_BACHELOR_DEGREE",
  KSIT_ASSOCIATE_DEGREE: "KSIT_ASSOCIATE_DEGREE",
  KCIT_ASSOCIATE_DEGREE: "KCIT_ASSOCIATE_DEGREE",
  RUPP_BACHELOR_DEGREE: "RUPP_BACHELOR_DEGREE",
  RUPP_MASTER_DEGREE: "RUPP_MASTER_DEGREE",
  RUPP_TRANSCRIPT: "RUPP_TRANSCRIPT",
  KCNIA_ASSOCIATE_DEGREE: "KCNIA_ASSOCIATE_DEGREE",
  KCNIA_BACHELOR_DEGREE: "KCNIA_BACHELOR_DEGREE",
  UHS_BACHELOR_DEGREE: "UHS_BACHELOR_DEGREE",
  UHS_ASSOCIATE_DEGREE: "UHS_ASSOCIATE_DEGREE",
  UHS_DOCTORATE_DEGREE: "UHS_DOCTORATE_DEGREE",
  NMU_ASSOCIATE_DEGREE: "NMU_ASSOCIATE_DEGREE",
  NMU_BACHELOR_DEGREE: "NMU_BACHELOR_DEGREE",
  NMU_MASTER_DEGREE: "NMU_MASTER_DEGREE",
  NIE_PHD_CERTIFICATE: "NIE_PHD_CERTIFICATE",
  NIE_MASTER_FRENCH_CERTIFICATE: "NIE_MASTER_FRENCH_CERTIFICATE",
  NIE_MASTER_EDUCATION_DEGREE: "NIE_MASTER_EDUCATION_DEGREE",
  NIA_ASSOCIATE_DEGREE: "NIA_ASSOCIATE_DEGREE",
  RUA_BACHELOR_DEGREE: "RUA_BACHELOR_DEGREE",
  RUA_MASTER_DEGREE: "RUA_MASTER_DEGREE",
  RUA_PHD_DEGREE: "RUA_PHD_DEGREE",
  KCIT_TEMPORARY_ASSOCIATE_CERTIFICATE: "KCIT_TEMPORARY_ASSOCIATE_CERTIFICATE",
  KCIT_TEMPORARY_BACHELOR_CERTIFICATE: "KCIT_TEMPORARY_BACHELOR_CERTIFICATE",
  DGC_GOVTECH_CERTIFICATE_OF_APPRECIATION:
    "DGC_GOVTECH_CERTIFICATE_OF_APPRECIATION",
  RUFA_BACHELOR_DEGREE: "RUFA_BACHELOR_DEGREE",
  SRU_TEMPORARY_BACHELOR_CERTIFICATE: "SRU_TEMPORARY_BACHELOR_CERTIFICATE",
  SRU_TEMPORARY_ASSOCIATE_CERTIFICATE: "SRU_TEMPORARY_ASSOCIATE_CERTIFICATE",
  MOEYS_BACII_CERTIFICATE_2023: "MOEYS_BACII_CERTIFICATE_2023",
  RUFA_STUDENT_ID_CARD: "RUFA_STUDENT_ID_CARD",
  KSIT_BACHELOR_DEGREE: "KSIT_BACHELOR_DEGREE",
  KSIT_ASSOCIATE_DEGREE: "KSIT_ASSOCIATE_DEGREE",
  RULE_BACHELOR_DEGREE: "RULE_BACHELOR_DEGREE",
  RUPP_FRANCE_BACHELOR_DEGREE: "RUPP_FRANCE_BACHELOR_DEGREE",
  AUPP_MASTER_CERTIFICATE_2024: "AUPP_MASTER_CERTIFICATE_2024",
  AUPP_BACHELOR_CERTIFICATE_2024: "AUPP_BACHELOR_CERTIFICATE_2024",
  MOINFO_GDINB_FREELANCER_CARD: "MOINFO_GDINB_FREELANCER_CARD",
  MOINFO_GDINB_FREELANCER_CARD: "MOINFO_GDINB_FREELANCER_CARD",
  MOINFO_STAFF_CARD: "MOINFO_STAFF_CARD",
  MPTC_TECHO_DIGITAL_SCHOLARSHIP_CERTIFICATE:
    "MPTC_TECHO_DIGITAL_SCHOLARSHIP_CERTIFICATE",
  MOC_INCORPORATION_CERTIFICATE: "MOC_INCORPORATION_CERTIFICATE",
  KCNIA_BACHELOR_DEGREE: "KCNIA_BACHELOR_DEGREE",
  KCNIA_ASSOCIATE_DEGREE: "KCNIA_ASSOCIATE_DEGREE",
  MPTC_INTERNSHIP_CERTIFICATE: "MPTC_INTERNSHIP_CERTIFICATE",
  MOINFO_TRAINING_CERTIFICATE_2024: "MOINFO_TRAINING_CERTIFICATE_2024",
  MOINSPECTION_INSPECTION_TRAINING_CERTIFICATE:
    "MOINSPECTION_INSPECTION_TRAINING_CERTIFICATE",
  MPTC_GDA_3RD_WORKSHOP_WORK_PERFORMANCE_CERTIFICATE:
    "MPTC_GDA_3RD_WORKSHOP_WORK_PERFORMANCE_CERTIFICATE",
  NIA_ASSOCIATE_DEGREE: "NIA_ASSOCIATE_DEGREE",
  NIA_BACHELOR_DEGREE: "NIA_BACHELOR_DEGREE",
  NIA_MASTER_DEGREE: "NIA_MASTER_DEGREE",
  BIU_BACHELOR_DEGREE: "BIU_BACHELOR_DEGREE",
  MPTC_GDA_3RD_WORKSHOP_WORK_PERFORMANCE_CERTIFICATE_PP:
    "MPTC_GDA_3RD_WORKSHOP_WORK_PERFORMANCE_CERTIFICATE_PP",
  MPTC_GDA_3RD_WORKSHOP_WORK_PERFORMANCE_COORDINATOR_CERTIFICATE:
    "MPTC_GDA_3RD_WORKSHOP_WORK_PERFORMANCE_COORDINATOR_CERTIFICATE",
  DGC_DCA_WORKSHOP_CERTIFICATE: "DGC_DCA_WORKSHOP_CERTIFICATE",
  BIU_DOCTOR_DEGREE: "BIU_DOCTOR_DEGREE",
  RUA_ASSOCIATE_DEGREE: "RUA_ASSOCIATE_DEGREE",
  DGC_DCA_WORKSHOP_CERTIFICATE: "DGC_DCA_WORKSHOP_CERTIFICATE",
  BIU_DOCTOR_DEGREE: "BIU_DOCTOR_DEGREE",
  MPTC_AUDIT_PERFORMANCE_WORKSHOP_CERTIFICATE:
    "MPTC_AUDIT_PERFORMANCE_WORKSHOP_CERTIFICATE",
  MPTC_EMBRACING_DIGITAL_TRANSFORMATION_APPRECIATION_CERTIFICATE:
    "MPTC_EMBRACING_DIGITAL_TRANSFORMATION_APPRECIATION_CERTIFICATE",
  MPTC_AUDIT_PERFORMANCE_WORKSHOP_CERTIFICATE:
    "MPTC_AUDIT_PERFORMANCE_WORKSHOP_CERTIFICATE",
  MPTC_EMBRACING_DIGITAL_TRANSFORMATION_RECOGNITION_CERTIFICATE:
    "MPTC_EMBRACING_DIGITAL_TRANSFORMATION_RECOGNITION_CERTIFICATE",
  AUPP_BACHELOR_DEGREE_SUMMER_2024: "AUPP_BACHELOR_DEGREE_SUMMER_2024",
  MPTC_DSLP_TRAINING_OF_TRAINERS_CERTIFICATE:
    "MPTC_DSLP_TRAINING_OF_TRAINERS_CERTIFICATE",
  RUA_DOCTOR_DEGREE: "RUA_DOCTOR_DEGREE",
  SSFA_TEMPORARY_ART_CERTIFICATE: "SSFA_TEMPORARY_ART_CERTIFICATE",
  SSFA_TEMPORARY_BACCALUARATE_CERTIFICATE:
    "SSFA_TEMPORARY_BACCALUARATE_CERTIFICATE",
  CADT_EMBRACING_DIGITAL_TRANSFORMATION_APPRECIATION_CERTIFICATE:
    "CADT_EMBRACING_DIGITAL_TRANSFORMATION_APPRECIATION_CERTIFICATE",
  CADT_EMBRACING_DIGITAL_TRANSFORMATION_RECOGNITION_CERTIFICATE:
    "CADT_EMBRACING_DIGITAL_TRANSFORMATION_RECOGNITION_CERTIFICATE",
  MFAIC_KHMER_IDENTITY_CARD: "MFAIC_KHMER_IDENTITY_CARD",
  MPTC_GOVTECH_CONFERENCE_APPRECIATION_CERTIFICATE:
    "MPTC_GOVTECH_CONFERENCE_APPRECIATION_CERTIFICATE",
  MPTC_AI_FORUM_APPRECIATION_CERTIFICATE:
    "MPTC_AI_FORUM_APPRECIATION_CERTIFICATE",
  MPTC_CDA_APPRECIATION_CERTIFICATE: "MPTC_CDA_APPRECIATION_CERTIFICATE",
  MPTC_INTERNSHIP_COMPLETION_CERTIFICATE:
    "MPTC_INTERNSHIP_COMPLETION_CERTIFICATE",
  MOT_OFFICIAL_ID_CARD: "MOT_OFFICIAL_ID_CARD",
  MPTC_CYBER_SECURITY_AWARENESS_MONTH_APPRECIATION_CERTIFICATE:
    "MPTC_CYBER_SECURITY_AWARENESS_MONTH_APPRECIATION_CERTIFICATE",
  MOINFO_GDINB_PRESS_CARD_CAMDX: "MOINFO_GDINB_PRESS_CARD_CAMDX",
  MPTC_LEADERSHIP_INNOVATION_APPRECIATION_CERTIFICATE:
    "MPTC_LEADERSHIP_INNOVATION_APPRECIATION_CERTIFICATE",
  SSFA_BACCALAUREATE_ARTS_DEGREE: "SSFA_BACCALAUREATE_ARTS_DEGREE",
  BIU_MASTER_DEGREE: "BIU_MASTER_DEGREE",
  MPTC_TRC_RIA_TRAINING_RECOGNITION_CERTIFICATE:
    "MPTC_TRC_RIA_TRAINING_RECOGNITION_CERTIFICATE",
  MPTC_TECHO_DIGITAL_SCHOLARSHIP_CERTIFICATE_2025:
    "MPTC_TECHO_DIGITAL_SCHOLARSHIP_CERTIFICATE_2025",
  BIU_ASSOCIATE_DEGREE: "BIU_ASSOCIATE_DEGREE",
  PPCA_OWS_TOURISM_LICENSE_CERTIFICATE: "PPCA_OWS_TOURISM_LICENSE_CERTIFICATE",
  MPTC_CYBERSECURITY_TRAIN_THE_TRAINER_PROGRAM_RECOGNITION_CERTIFICATE:
    "MPTC_CYBERSECURITY_TRAIN_THE_TRAINER_PROGRAM_RECOGNITION_CERTIFICATE",
  AUPP_MASTER_DEGREE_2025: "AUPP_MASTER_DEGREE_2025",
  NIE_PHD_DEGREE: "NIE_PHD_DEGREE",
  AUPP_ATC_INNOVATION_ECOSYSTEM_MENTOR_COMPLETION_CERTIFICATE:
    "AUPP_ATC_INNOVATION_ECOSYSTEM_MENTOR_COMPLETION_CERTIFICATE",
  RULE_MASTER_DEGREE: "RULE_MASTER_DEGREE",
  MOINFO_BASIC_TECHNICAL_TRAINING_CERTIFICATE:
    "MOINFO_BASIC_TECHNICAL_TRAINING_CERTIFICATE",
  MPTC_CNCC_ACHIEVEMENT_CERTIFICATE: "MPTC_CNCC_ACHIEVEMENT_CERTIFICATE",
  CADT_CYBER_RESILIENCE_AND_SAFETY_CULTURE_CERTIFICATE:
    "CADT_CYBER_RESILIENCE_AND_SAFETY_CULTURE_CERTIFICATE",
  RUPP_PHD_DEGREE: "RUPP_PHD_DEGREE",
  MOT_TOURIST_GUIDE_LICENSE_CARD: "MOT_TOURIST_GUIDE_LICENSE_CARD",
  MOINFO_BASIC_TECHNICAL_TRAINING_CERTIFICATE:
    "MOINFO_BASIC_TECHNICAL_TRAINING_CERTIFICATE",
  MPTC_CNCC_ACHIEVEMENT_CERTIFICATE: "MPTC_CNCC_ACHIEVEMENT_CERTIFICATE",
  CADT_CYBER_RESILIENCE_AND_SAFETY_CULTURE_CERTIFICATE:
    "CADT_CYBER_RESILIENCE_AND_SAFETY_CULTURE_CERTIFICATE",
  RUPP_PHD_DEGREE: "RUPP_PHD_DEGREE",
  MPTC_NATIONAL_LETTER_WRITING_COMPETITION_RECOGNITION_CERTIFICATE:
    "MPTC_NATIONAL_LETTER_WRITING_COMPETITION_RECOGNITION_CERTIFICATE",
  MPTC_DIGITAL_ADOPTION_FOR_WORK_EFFICIENCY_RECOGNITION_CERTIFICATE:
    "MPTC_DIGITAL_ADOPTION_FOR_WORK_EFFICIENCY_RECOGNITION_CERTIFICATE",
  MPTC_DIGITAL_TECHNOLOGY_SKILLS_TRAINER_COMPLETION_CERTIFICATE:
    "MPTC_DIGITAL_TECHNOLOGY_SKILLS_TRAINER_COMPLETION_CERTIFICATE",
  MOT_TOURIST_GUIDE_LICENSE_CARD: "MOT_TOURIST_GUIDE_LICENSE_CARD",
  MOT_CONTRACTUAL_STAFF_ID_CARD: "MOT_CONTRACTUAL_STAFF_ID_CARD",
  DICHI_ELIX_COMPLETION_CERTIFICATE: "DICHI_ELIX_COMPLETION_CERTIFICATE",
  MPTC_DATA_DRIVEN_WORK_COMPLETION_CERTIFICATE:
    "MPTC_DATA_DRIVEN_WORK_COMPLETION_CERTIFICATE",
  MOT_INTERPRETER_FROM_TOURIST_GUIDE_PERMISSION_CARD:
    "MOT_INTERPRETER_FROM_TOURIST_GUIDE_PERMISSION_CARD",
  MPTC_DIGITAL_ADOPTION_FOR_WORK_EFFICIENCY_APPRECIATION_CERTIFICATE:
    "MPTC_DIGITAL_ADOPTION_FOR_WORK_EFFICIENCY_APPRECIATION_CERTIFICATE",
  KSIT_ASSOCIATE_CERTIFICATE: "KSIT_ASSOCIATE_CERTIFICATE",
  KSIT_BACHELOR_CERTIFICATE: "KSIT_BACHELOR_CERTIFICATE",
  SRU_MASTER_DEGREE: "SRU_MASTER_DEGREE",
  SRU_ASSOCIATE_DEGREE: "SRU_ASSOCIATE_DEGREE",
  SRU_BACHELOR_DEGREE: "SRU_BACHELOR_DEGREE",
  SERC_DERIVATIVES_REPRESENTATIVE_LICENCE_CARD:
    "SERC_DERIVATIVES_REPRESENTATIVE_LICENCE_CARD",
  SERC_CENTRAL_COUNTERPARTY_LICENCE_CERTIFICATE:
    "SERC_CENTRAL_COUNTERPARTY_LICENCE_CERTIFICATE",
  SERC_IT_PROVIDER_SECURITIES_AUTHORIZATION_CERTIFICATE:
    "SERC_IT_PROVIDER_SECURITIES_AUTHORIZATION_CERTIFICATE",
  MPTC_ONLINE_SAFETY_FORUM_2025_CERTIFICATE:
    "MPTC_ONLINE_SAFETY_FORUM_2025_CERTIFICATE",
  SERC_PARTICIPATION_FINANCIAL_TECHNOLOGY_REGULATORY_SANDBOX_AUTHORIZATION_CERTIFICATE:
    "SERC_PARTICIPATION_FINANCIAL_TECHNOLOGY_REGULATORY_SANDBOX_AUTHORIZATION_CERTIFICATE",
  SERC_FUND_DISTRIBUTION_REDEMPTION_PAYMENT_COMPANY_AUTHORIZATION_CERTIFICATE:
    "SERC_FUND_DISTRIBUTION_REDEMPTION_PAYMENT_COMPANY_AUTHORIZATION_CERTIFICATE",
  SERC_FINANCIAL_ADVISORY_COMPANY_AUTHORIZATION_CERTIFICATE:
    "SERC_FINANCIAL_ADVISORY_COMPANY_AUTHORIZATION_CERTIFICATE",
  SERC_INVESTMENT_ADVISORY_COMPANY_AUTHORIZATION_CERTIFICATE:
    "SERC_INVESTMENT_ADVISORY_COMPANY_AUTHORIZATION_CERTIFICATE",
  SERC_FUND_TRUSTEE_COMPANY_AUTHORIZATION_CERTIFICATE:
    "SERC_FUND_TRUSTEE_COMPANY_AUTHORIZATION_CERTIFICATE",
  SERC_GOVERNMENT_SECURITIES_DEALER_AUTHORIZATION_CERTIFICATE:
    "SERC_GOVERNMENT_SECURITIES_DEALER_AUTHORIZATION_CERTIFICATE",
  SERC_SECURITIES_CLEARING_SETTLEMENT_SYSTEM_OPERATOR_AUTHORIZATION_CERTIFICATE:
    "SERC_SECURITIES_CLEARING_SETTLEMENT_SYSTEM_OPERATOR_AUTHORIZATION_CERTIFICATE",
  SERC_SECURITIES_CUSTODIAN_OPERATOR_AUTHORIZATION_CERTIFICATE:
    "SERC_SECURITIES_CUSTODIAN_OPERATOR_AUTHORIZATION_CERTIFICATE",
  SERC_SECURITIES_DISTRIBUTION_COMPANY_AUTHORIZATION_CERTIFICATE:
    "SERC_SECURITIES_DISTRIBUTION_COMPANY_AUTHORIZATION_CERTIFICATE",
  SERC_SECURITIES_MARKET_OPERATOR_AUTHORIZATION_CERTIFICATE:
    "SERC_SECURITIES_MARKET_OPERATOR_AUTHORIZATION_CERTIFICATE",
  SERC_DERIVATIVES_BROKER_LICENCE_CERTIFICATE:
    "SERC_DERIVATIVES_BROKER_LICENCE_CERTIFICATE",
  SERC_FINANCIAL_ADVISORY_LICENCE_CERTIFICATE:
    "SERC_FINANCIAL_ADVISORY_LICENCE_CERTIFICATE",
  SERC_FUND_MANAGEMENT_LICENSE_CERTIFICATE:
    "SERC_FUND_MANAGEMENT_LICENSE_CERTIFICATE",
  SERC_DERIVATIVES_BROKER_AUTHORIZATION_CERTIFICATE:
    "SERC_DERIVATIVES_BROKER_AUTHORIZATION_CERTIFICATE",
  KCIT_BACHELOR_DEGREE: "KCIT_BACHELOR_DEGREE",
  KCIT_ASSOCIATE_DEGREE: "KCIT_ASSOCIATE_DEGREE",
  MOCAR_DHARMA_DISCIPLINE_CERTIFICATE: "MOCAR_DHARMA_DISCIPLINE_CERTIFICATE",
  MOCAR_PRIMARY_SCHOOL_BUDDHIST_STUDY_CERTIFICATE:
    "MOCAR_PRIMARY_SCHOOL_BUDDHIST_STUDY_CERTIFICATE",
  NMU_ASSOCIATE_DEGREE: "NMU_ASSOCIATE_DEGREE",
  NMU_BACHELOR_DEGREE: "NMU_BACHELOR_DEGREE",
  NMU_MASTER_DEGREE: "NMU_MASTER_DEGREE",
  SERC_IT_PROVIDER_REPRESENTATIVE_AUTHORIZATION_CARD:
    "SERC_IT_PROVIDER_REPRESENTATIVE_AUTHORIZATION_CARD",
  MOCAR_HIGH_SCHOOL_BUDDHIST_STUDY_TEMPORARY_CERTIFICATE:
    "MOCAR_HIGH_SCHOOL_BUDDHIST_STUDY_TEMPORARY_CERTIFICATE",
  MOCAR_HIGH_SCHOOL_BUDDHIST_STUDY_CERTIFICATE:
    "MOCAR_HIGH_SCHOOL_BUDDHIST_STUDY_CERTIFICATE",
  TRC_RADIO_TELECOM_EQUIPMENT_RECOGNITION_CERTIFICATE:
    "TRC_RADIO_TELECOM_EQUIPMENT_RECOGNITION_CERTIFICATE",
  SERC_CROWNFUNDING_REPRESENTATIVE_LICENCE_CARD:
    "SERC_CROWNFUNDING_REPRESENTATIVE_LICENCE_CARD",
  SERC_FINANCIAL_ADVISORY_REPRESENTATIVE_LICENCE_CARD:
    "SERC_FINANCIAL_ADVISORY_REPRESENTATIVE_LICENCE_CARD",
  SERC_FUND_MANAGEMENT_REPRESENTATIVE_LICENSE_CARD:
    "SERC_FUND_MANAGEMENT_REPRESENTATIVE_LICENSE_CARD",
  SERC_FUND_SELLLING_REPRESENTATIVE_LICENCE_CARD:
    "SERC_FUND_SELLLING_REPRESENTATIVE_LICENCE_CARD",
  SERC_SECURITIES_REPRESENTATIVE_LICENCE_CARD:
    "SERC_SECURITIES_REPRESENTATIVE_LICENCE_CARD",
  MOCAR_PRIMARY_SCHOOL_BUDDHIST_STUDY_DEGREE:
    "MOCAR_PRIMARY_SCHOOL_BUDDHIST_STUDY_DEGREE",
  MOCAR_SECONDARY_SCHOOL_BUDDHIST_STUDY_CERTIFICATE:
    "MOCAR_SECONDARY_SCHOOL_BUDDHIST_STUDY_CERTIFICATE",
  AUPP_MASTER_CERTIFICATE_2022: "AUPP_MASTER_CERTIFICATE_2022",
  AUPP_BACHELOR_DEGREE_SUMMER_2025: "AUPP_BACHELOR_DEGREE_SUMMER_2025",
  AUPP_MASTER_DEGREE_SUMMER_2025: "AUPP_MASTER_DEGREE_SUMMER_2025",
  MPTC_ICT_LMC_CERTIFICATE: "MPTC_ICT_LMC_CERTIFICATE",
  MPTC_PERSONAL_DATA_PROTECTION_APPRECIATION_CERTIFICATE:
    "MPTC_PERSONAL_DATA_PROTECTION_APPRECIATION_CERTIFICATE",
  NIE_INSPECTOR_DEGREE: "NIE_INSPECTOR_DEGREE",
  NIE_FRENCH_MASTER_DEGREE: "NIE_FRENCH_MASTER_DEGREE",
  NIE_MASTER_DEGREE: "NIE_MASTER_DEGREE",
  MPTC_CDA_2025_AWARD_CERTIFICATE: "MPTC_CDA_2025_AWARD_CERTIFICATE",
  MPTC_CDA_2025_APPRECIATION_CERTIFICATE:
    "MPTC_CDA_2025_APPRECIATION_CERTIFICATE",
  CAMTECH_BACHELOR_DEGREE: "CAMTECH_BACHELOR_DEGREE",
  CAMTECH_MASTER_DEGREE: "CAMTECH_MASTER_DEGREE",
  CAMTECH_PHD_DEGREE: "CAMTECH_PHD_DEGREE",
  CAMTECH_TRAINING_CERTIFICATE: "CAMTECH_TRAINING_CERTIFICATE",
  MPTC_DGF_2025_VOLUNTEER_APPRECIATION_CERTIFICATE:
    "MPTC_DGF_2025_VOLUNTEER_APPRECIATION_CERTIFICATE",
  MOINFO_GDINB_PRESS_CARD_2026: "MOINFO_GDINB_PRESS_CARD_2026",
  MPTC_DSLP_RECOGNITION_CERTIFICATE: "MPTC_DSLP_RECOGNITION_CERTIFICATE",
  MPTC_PDP_WORKSHOP_CERTIFICATE: "MPTC_PDP_WORKSHOP_CERTIFICATE",
  CPFAC_ANNOUNCEMENT: "CPFAC_ANNOUNCEMENT",
  CPFAC_PRODUCT_SPECIFICATION_CERTIFICATE:
    "CPFAC_PRODUCT_SPECIFICATION_CERTIFICATE",
  AUPP_BACHELOR_DEGREE_FALL_2025: "AUPP_BACHELOR_DEGREE_FALL_2025",
  AUPP_MASTER_DEGREE_FALL_2025: "AUPP_MASTER_DEGREE_FALL_2025",
  CPFCA_PRODUCT_SPECIFICATION_CERTIFICATE:
    "CPFCA_PRODUCT_SPECIFICATION_CERTIFICATE",
  MPTC_CYBERSECURITY_WORKSHOP_2026_CERTIFICATE:
    "MPTC_CYBERSECURITY_WORKSHOP_2026_CERTIFICATE",
  MOT_CHINA_ACCREDITED_CARD: "MOT_CHINA_ACCREDITED_CARD",
  MPTC_TRAINING_BDS_RECOGNITION_CERTIFICATE:
    "MPTC_TRAINING_BDS_RECOGNITION_CERTIFICATE",
  MOT_CHINA_ACCREDITED_CERTIFICATE: "MOT_CHINA_ACCREDITED_CERTIFICATE",
  AUPP_NEW_CERTIFICATE: "AUPP_NEW_CERTIFICATE",
  MPTC_INTERNSHIP_CERTIFICATE_2026: "MPTC_INTERNSHIP_CERTIFICATE_2026",
  MPTC_UNIDIR_COMPLETION_CERTIFICATE: "MPTC_UNIDIR_COMPLETION_CERTIFICATE",
  MPTC_GDA_CARD: "MPTC_GDA_CARD",
  SSFA_DIPLOMA_DEGREE: "SSFA_DIPLOMA_DEGREE",
  MOINSPECTION_OFFICIAL_ID_CARD: "MOINSPECTION_OFFICIAL_ID_CARD",
  MOP_NSPS_PARTICIPATION_CERTIFICATE: "MOP_NSPS_PARTICIPATION_CERTIFICATE",
  MOINFO_CONTRACTUAL_STAFF_CARD: "MOINFO_CONTRACTUAL_STAFF_CARD",
  AUPP_POSTGRADUATE_CERTIFICATE: "AUPP_POSTGRADUATE_CERTIFICATE",
  MPTC_NATIONAL_LETTER_WRITING_COMPETITION_RECOGNITION_CERTIFICATE_2026:
    "MPTC_NATIONAL_LETTER_WRITING_COMPETITION_RECOGNITION_CERTIFICATE_2026",
  MPTC_ADSEPSD_COMPLETION_CERTIFICATE: "MPTC_ADSEPSD_COMPLETION_CERTIFICATE",
  MPTC_NATIONAL_LETTER_WRITING_APPRECIATION_CERTIFICATE_2026:
    "MPTC_NATIONAL_LETTER_WRITING_APPRECIATION_CERTIFICATE_2026",
  FSA_OFFICIAL_ID_CARD: 'FSA_OFFICIAL_ID_CARD',
  MPTC_CYBER_INCIDENT_RESPONSE_CERTIFICATE: 'MPTC_CYBER_INCIDENT_RESPONSE_CERTIFICATE',
  PPCA_OWS_HEALTH_HYGIENE_CERTIFICATE: 'PPCA_OWS_HEALTH_HYGIENE_CERTIFICATE',
  PPCA_OWS_CHAMKARMORN_TOURISM_LICENSE_CERTIFICATE: 'PPCA_OWS_CHAMKARMORN_TOURISM_LICENSE_CERTIFICATE',
  MPTC_ICT_LANCANG_MEKONG_REGIONAL_CYBERSECURITY_FORUM_CERTIFICATE: 'MPTC_ICT_LANCANG_MEKONG_REGIONAL_CYBERSECURITY_FORUM_CERTIFICATE',
};
